### PR TITLE
recipient_delimiter is allowed to be empty

### LINKED ISSUE #1370: Doesn't switch to the faulty tab
# Steps to reproduce
Go to parameters and select the Amavis tab. Empty the recipient delimiter field (where a value is required). Don't save and go back to the General tab. Click on save in this tab.

# Current behavior
Nothing happens. You cannot save but nothing is printed and you are not switched to the tab with an error.

# Expected behavior
Switch to the tab with the error or at least, print a message.

### LINKED ISSUE #1371: Not able to save Parameters
# Impacted versions

* Modoboa: 1.10.1
* installer used: Yes
* Webserver: Nginx

# Steps to reproduce
New setup, after login and password change, I am not able to save parameter settings. Nothing happend on pressing SAVE button

### PR DESCRIPTION
**Pull request by ghost**
fixes modoboa/modoboa#1371
fixes modoboa/modoboa#1370

### CODE REVIEW

**Comment by fresH229a** [comment]
Hey,

I am not sure but can this be modifed on an already installed version?
I tried it but then, i just got a json opened in browser :-S

**Comment by tonioo** [comment]
@fresH229a Just put a value (like +) as recipient delimiter and it should work.

**Comment by tonioo** [comment]
@fyfe What about a default value instead? (like +)

**Comment by fresH229a** [comment]
@tonioo To save the settings you need to put recipient delimiter + Server URL of the radical tab, then the settings get saved :)

**Comment by fyfe** [comment]
Because it needs to match amavis and its default is empty.

On January 29, 2018 12:01:59 PM UTC, Antoine Nguyen <notifications@github.com> wrote:
>@fyfe What about a default value instead? (like +)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/modoboa/modoboa-amavis/pull/93#issuecomment-361224851

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fresH229a** [comment]
@fyfe I have changed it in the file: /srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/forms.py but still have the same issue. It is not saving if the field is empty. :-S

**Comment by fyfe** [comment]
@fresH229a do you have modoboa-radical installed as well? It has a similar issue modoboa/modoboa-radicale#19

**Comment by fresH229a** [comment]
@fyfe Nope, I dont have :)

**Comment by fyfe** [comment]
@fresH229a can you open your browsers developer console and see if there's any errors?

Internet Explorer / Chrome : `F12`
Firefox: `Ctrl+Shift+K`

**Comment by fresH229a** [comment]
@fyfe I can yep, what should i do ? :)

**Comment by fyfe** [comment]
- open the developer console for your browser 
- set `recipient delimiter` to an empty value
- click save

Check the console and see if there's any errors.

To open the developer console press `F12` for Internet Explorer / Microsoft Edge / Chrome or `Ctrl+Shift+K` for Firefox.

@fresH229a have you restarted modoboa after modifying forms.py? Changes don't take effect until modoboa has been restarted.

**Comment by fresH229a** [comment]
@fyfe  yep, whole server restarted.
No i can not see any error, (probably I am looking wrongly..)

**Comment by fyfe** [comment]
_Silly question time_ is anything displayed when you try and save with the field empty? If nothing is displayed, close you're browser and reopen it and see if the field is still empty.


@tonioo the main problem with this is that Django is trying to validate all the fields from all the tabs as settings is treated as *one* big form. I think they need separated out into one form per tab this would make it easier to display errors to the use, but I'm not sure if that's possible with the current modular form that's used for settings. Roll on modoboa/modoboa#1320

**Comment by fresH229a** [comment]
@fyfe nothing, its just doing nothing :)

**Comment by fyfe** [comment]
Then it's probably saving, can you try changing another field (eg `Maximum message age`) and see if it saves.

Which browser (and version) are you using?

**Comment by fresH229a** [comment]
Already tried, its not saved :( Mozilla latest version. Tried it with IE (no addons) too, same issue.

**Comment by fyfe** [comment]
What indication do you get that it's not saved? Is there another value in the field (ie it's not blank)?

I'm running out of ideas, in `settings.py` set `ADMINS` and it'll send error messages to that e-mail address, in case something failing silently in the background:

```python
# A list of all the people who get code error notifications. When DEBUG=False
# and a view raises an exception, Django will email these people with the full
# exception information.
# See https://docs.djangoproject.com/en/dev/ref/settings/#admins
ADMINS = [('Administrator', 'admin@example.com')]

# The email address that error messages come from, such as those sent to ADMINS
SERVER_EMAIL = 'notifications@example.com'
```

**Comment by fresH229a** [comment]
Okay, I reinstalled the whole vserver with modoaboa and start again.

1 error:
`loading pref showConsoleLogs before prefs were initialised, you will not get the correct result
content-script.bundle.js:333:7
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead
[Weitere Informationen]
jquery.min.js:1
getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.`

I got a error mail but can I send it to you personally?

I recognize it simply if i click "send statistic" -> NO and then press save, nothing happend. If I go than to the Amavis Tab and press save, it jumps back to General TAB and the setting "NO" is still active but if i reload the site, the setting is again "yes".

You can also have a look directly on my server (its cleaned installed without personal data if it helps to find the solution)

**Comment by tonioo** [comment]
The issue with parameters is due to the browser-side validation which is not disabled by the form. Since there are empty fields, no request is sent to the server and, since empty fields are hidden, they can't be focused. (this is what Chrome tells you in the console) A quickfix for this could be to disable browser-side auto validation.

**Comment by fresH229a** [comment]
I tried it to do it in Firefox but wasnt able to solve the issue with this workaround.
Have you tried it in chrome?

**Comment by fyfe** [comment]
@tonioo  I didn't know that, the short term solution then is to add [novalidate](https://www.w3schools.com/tags/att_form_novalidate.asp) to the [html form](https://github.com/modoboa/modoboa/blob/c9f818cf84528ace74c3e623fc5b63df59491fc1/modoboa/core/templates/core/parameters.html#L3).

**Comment by fresH229a** [comment]
@fyfe will test this in a few minutes (need to load the default snapshot) :)

**Comment by fresH229a** [comment]
@fyfe Unfortunately, this does not solve the problem. It is still not saving :( Tested with IE + Firefox + Chrome.

In chrome I saw no this error:

```
POST https://mx01.axgc.at/core/parameters/ 400 (Bad Request)
send @ jquery.min.js:5
ajax @ jquery.min.js:5
simple_ajax_form_post @ global.js:171
(anonymous) @ twocols_nav.js:40
i @ jquery.min.js:3
dispatch @ jquery.min.js:3
v.handle @ jquery.min.js:3
```

**Comment by fresH229a** [comment]
@fyfe  just an Idea ( i am noob) Could it be a problem that in the browser adress line is /core/**# #**parameters/ written 
That the form couldn't be completed cause there is a # (not sure how it was with old versions)

**Comment by fyfe** [comment]
@fresH229a No the #**paramters/ is used by javascript to switch between the tabs

In chrome can you try the following
image

**Comment by fresH229a** [comment]
Okay thats strange :D 
`{"prefix": "core", "form_errors": {"default_password": ["This password is too common.", "Password must contain at least 1 digit."]}}`

**Comment by tonioo** [comment]
@fyfe That's what I wanted to do :-)

**Comment by tonioo** [comment]
@fyfe What happens when not delimiter is defined?

**Comment by fyfe** [comment]
@tonioo if the delimiter isn't set it won't try looking up user+*@example.com addresses

https://github.com/modoboa/modoboa-amavis/blob/master/modoboa_amavis/lib.py#L424-L426

**Pull request merged**
